export { default as ProductCard } from '../../components/product/ProductCard/ProductCard'
export { default as ProductFeatured } from '../../components/product/ProductFeatured/ProductFeatured'
export { default as ProductHero } from '../../components/product/ProductHero/ProductHero'
export { default as ProductLinksCard } from '../../components/shared/ProductLinksCard/ProductLinksCard'
export { default as products } from './data/products'
